# pylint: skip-file
# Generated by Django 3.2.20 on 2023-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0022_amazonpurchase_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonASINItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=4096, unique=True)),
                ('item_name', models.CharField(default='Unknown Item', max_length=4096)),
                ('keepa_response', models.TextField(blank=True, max_length=8388608, null=True)),
                ('fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
