# Generated by Django 3.2.20 on 2024-01-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0024_alter_amazonasinitem_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonasinitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
